Java basic part2
Ivanenko16/Automation2021 pull request #4
Opened 2021-12-10 14:51 UTC by Ivanenko16

2021-12-12 14:31 UTC, ivanmatiashepam requested changes

2021-12-12 14:31 UTC, ivanmatiashepam commented on src/main/java/javaBasicPart2/Rectangle.java
> +    public int area() {
Please create constructor for Rectangle glass and make height and weight as a private variables (encapsulate them)

2021-12-12 14:31 UTC, ivanmatiashepam commented on src/main/java/javaBasicPart2/Computer.java
>      }
Please make class variable private (encapsulation OOP principle)

2021-12-12 14:31 UTC, ivanmatiashepam commented on src/main/java/javaBasicPart2/NumberHolder.java
> +
Please make these variables private and create some public get() methods for them. Use these methods to get value and print it

2021-12-13 10:09 UTC, Ivanenko16 commented on src/main/java/javaBasicPart2/Computer.java
>      }
I made all the variables for this class with a private status. If I understand your comment correctly. Please confirm

2021-12-13 10:09 UTC, Ivanenko16 commented on src/main/java/javaBasicPart2/NumberHolder.java
> +
Thanks for the comment, all tips have been applied.

2021-12-13 10:09 UTC, Ivanenko16 commented on src/main/java/javaBasicPart2/Rectangle.java
> +    public int area() {
Thanks for the comment, all tips have been applied.

2021-12-13 16:14 UTC, ivanmatiashepam commented on src/main/java/javaBasicPart2/Main.java
> +        Rectangle myRect = new Rectangle(50,40);
Please apply "Reformat code" action from IntelliJ Idea (Ctrl + Alt + L shortcut or from Code -> Reformat Code context menu) to the whole class

2021-12-13 16:14 UTC, ivanmatiashepam commented on src/main/java/javaBasicPart2/Rectangle.java
> +
very minor comment, but it would be better to rename this method according to Java conventions to something like getArea()

2021-12-13 16:14 UTC, ivanmatiashepam commented on src/main/java/javaBasicPart2/NumberHolder.java
> +    public float getaFloat() {
please rename to getAFloat, it is ok to have few uppercase characters for such cases

2021-12-13 16:14 UTC, ivanmatiashepam commented on src/main/java/javaBasicPart2/Computer.java
>      }
yeh, that's correct

2021-12-13 18:28 UTC, Ivanenko16 commented on src/main/java/javaBasicPart2/Rectangle.java
> +
fixed, thank you

2021-12-13 18:29 UTC, Ivanenko16 commented on src/main/java/javaBasicPart2/Main.java
> +        Rectangle myRect = new Rectangle(50,40);
fixed, thank you

2021-12-13 19:00 UTC, Ivanenko16 reviewed
done

2021-12-13 19:01 UTC, Ivanenko16 reviewed
done

2021-12-13 19:41 UTC, merged