java advanced is completed
Ivanenko16/Automation2021 pull request #7
Opened 2022-01-03 09:30 UTC by Ivanenko16

2022-01-05 14:48 UTC, ivanmatiashepam requested changes

2022-01-05 14:48 UTC, ivanmatiashepam commented on src/main/java/javaadvanced/task1/CharacterCount.java
> +    static void characterCount(String inputString) {
please change return type to Map according to the task

2022-01-05 14:48 UTC, ivanmatiashepam commented on src/main/java/javaadvanced/task2/SortableCollection.java
> +    static <V> void createSortableCollection(Collection<V> collection) {
Please use T keyword for Type. Also, please return this collection

2022-01-05 14:48 UTC, ivanmatiashepam commented on src/main/java/javaadvanced/task4/Run.java
> +        for (String str : orderHashSet) {
btw, you can also print the whole collection (if you do not need each value to be printed on a new line) - System.out.println(orderHashSet);

2022-01-05 14:48 UTC, ivanmatiashepam commented on src/main/java/javaadvanced/task5/Run.java
> +            } else {
we do not need this part of code according to the task. there shouldn't be such situation - if keys > values there would be an Exception

2022-01-06 10:31 UTC, Ivanenko16 commented on src/main/java/javaadvanced/task1/CharacterCount.java
> +    static void characterCount(String inputString) {
Type changed

2022-01-06 10:34 UTC, Ivanenko16 commented on src/main/java/javaadvanced/task2/SortableCollection.java
> +    static <V> void createSortableCollection(Collection<V> collection) {
Fixed

2022-01-06 10:41 UTC, Ivanenko16 commented on src/main/java/javaadvanced/task4/Run.java
> +        for (String str : orderHashSet) {
Absolutely agree), fixed

2022-01-06 10:45 UTC, Ivanenko16 commented on src/main/java/javaadvanced/task5/Run.java
> +            } else {
Fixed

2022-01-06 14:24 UTC, ivanmatiashepam commented on src/main/java/javaadvanced/task2/SortableCollection.java
> +    static <V> void createSortableCollection(Collection<V> collection) {
method is still void

2022-01-06 14:24 UTC, ivanmatiashepam commented on src/main/java/javaadvanced/task4/Run.java
> +        for (String str : orderHashSet) {
the same can be applied to the orderTreeSet as well, to have some common code style

2022-01-06 15:54 UTC, Ivanenko16 commented on src/main/java/javaadvanced/task2/SortableCollection.java
> +    static <V> void createSortableCollection(Collection<V> collection) {
The method changed (return collection)

2022-01-06 15:58 UTC, Ivanenko16 commented on src/main/java/javaadvanced/task4/Run.java
> +        for (String str : orderHashSet) {
Applied to the orderTreeSet too

2022-01-10 12:39 UTC, ivanmatiashepam commented on src/main/java/javaadvanced/task2/SortableCollection.java
> +    static <V> void createSortableCollection(Collection<V> collection) {
Please provide the parametrized type for this generic. should be - "static <T> Collection<T> createSortableCollection" (return collection's members type should be the same as the type for method's argument). 

Generic types shouldn’t be used raw (without type parameters) in variable declarations or return values. Doing so bypasses generic type checking, and defers the catch of unsafe code to runtime.

2022-01-10 13:12 UTC, Ivanenko16 commented on src/main/java/javaadvanced/task2/SortableCollection.java
> +    static <V> void createSortableCollection(Collection<V> collection) {
Fixed, thanks for the explanation

2022-01-10 13:13 UTC, merged