Streams
Ivanenko16/Automation2021 pull request #8
Opened 2022-01-16 19:30 UTC by Ivanenko16

MODULE 8: LAMBDA. STREAMS

2022-01-18 19:42 UTC, ivanmatiashepam requested changes

2022-01-18 19:42 UTC, ivanmatiashepam commented on src/main/java/streams/task1/Run.java
> +        List<String> listWithAllWords = returnListWithAllWords(text);
there is no need to create a separate list variable, your method returnListWithAllWords(text) can be used in the next line (or remove the method and just use text.split(" ") on the next line instead of listWithAllWords)

2022-01-18 19:42 UTC, ivanmatiashepam commented on src/main/java/streams/task3/Person.java
> +    public static List<Person> createListOfDistinctAdultPerson(List<Person> personList) {
good implementation! please create another method where all task is done in one stream. implementation can be simplified :)

2022-01-18 19:46 UTC, ivanmatiashepam requested changes

2022-01-18 19:46 UTC, ivanmatiashepam commented on src/main/java/streams/task1/Run.java
> +        FileInputStream fileInputStream = new FileInputStream("TestData");
please use try-catch here and close input stream in finally clause

2022-01-18 20:05 UTC, ivanmatiashepam requested changes

2022-01-18 20:05 UTC, ivanmatiashepam commented on src/main/java/streams/task2/Run.java
> +        List<Book> sortedListOfBooks = Book.createSortedListOfBooks(listOfRandomBooks);
Books should be sorted by names in descending order according to the task

2022-01-19 11:05 UTC, Ivanenko16 commented on src/main/java/streams/task1/Run.java
> +        List<String> listWithAllWords = returnListWithAllWords(text);
fixed

2022-01-19 11:06 UTC, Ivanenko16 commented on src/main/java/streams/task3/Person.java
> +    public static List<Person> createListOfDistinctAdultPerson(List<Person> personList) {
fixed, another single method created

2022-01-19 11:07 UTC, Ivanenko16 commented on src/main/java/streams/task1/Run.java
> +        FileInputStream fileInputStream = new FileInputStream("TestData");
fixed

2022-01-19 11:11 UTC, Ivanenko16 commented on src/main/java/streams/task2/Run.java
> +        List<Book> sortedListOfBooks = Book.createSortedListOfBooks(listOfRandomBooks);
fixed

2022-01-20 11:01 UTC, merged